//findAll
GET http://localhost:3003/posts
###
//findOne
GET http://localhost:3003/posts/ff4721ea-6fcb-45ec-975e-de1264e64726
###
//create
POST http://localhost:3003/posts
Content-Type: application/json

{ 
  "title": "Teste",
  "body": "Toguro Lorem Ipsum"
}

###
//update
PUT  http://localhost:3003/posts/c5848e01-5c7d-4512-9694-7337389066be
Content-Type: application/json

{ 
  "title": "Update funfou",
  "body": "Sucesso"
}
###
//delete
DELETE  http://localhost:3003/posts/c5848e01-5c7d-4512-9694-7337389066be