//findAll
GET http://localhost:3003/posts
###
//findOne
GET http://localhost:3003/posts/ff4721ea-6fcb-45ec-975e-de1264e64726
###
//create
POST http://localhost:3003/posts
Content-Type: application/json

{ 
  "title": "Jurandir",
  "body": "Toguro Lorem Ipsum"
}

###
//update
PUT  http://localhost:3003/posts/f3239a8f-a566-467e-9228-97a308d30a9e
Content-Type: application/json

{ 
  "title": "Quarta",
  "body": "Toguro Lorem Ipsum"
}
###
//delete
DELETE  http://localhost:3003/posts/c5848e01-5c7d-4512-9694-7337389066be
###

//findHistoryByd
GET http://localhost:3003/history/f3239a8f-a566-467e-9228-97a308d30a9e